apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policy-app
  namespace: argocd
spec:
  destination:
    namespace: nginx-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: policy/
    repoURL: https://github.com/sanjeev-choudhary/gatekeeper-policy.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true